# vfabingazure-pipelines-agent-dotnet-core-sdk
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: azure-agent
  name: azure-agent
spec:
  replicas: 1
  revisionHistoryLimit: 2 #保留的历史记录数，设置为0将清理部署的所有历史记录，无法回滚
  strategy:
    rollingUpdate: #滚动更新配置
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate #使用滚动更新策略
  template:
    metadata:
      labels:
        app: azure-agent
    spec:
      containers:
      - env:
        - name: AZP_URL
          value: http://172.16.2.189
        - name: AZP_AGENT_NAME
          value: Agent1
        - name: AZP_TOKEN
          value: t4nfv7zlnjoyfmano5g6sg7zwipszfbgynjzcjazspadhvchuvoq
          # AZP_POOL	Agent pool name (default value: Default)
          # AZP_WORK	Work directory (default value: _work)
        - name: DOCKER_IN_DOCKER
          value: start
        image: vfabing/azure-pipelines-agent-dotnet-core-sdk
        imagePullPolicy: Always
        name: azure-agent
        resources: #资源限制
          limits:
            cpu: 4
            memory: 10024Mi
          requests: #代理构建时消耗比较大，尽量分配多点资源
            cpu: 1
            memory: 2096Mi
        securityContext:
          privileged: true #特级权限
        volumeMounts:
        - mountPath: /data/teamcity_agent/conf
          name: vol
        - mountPath: /var/lib/docker
          name: vol
      dnsPolicy: ClusterFirst
      nodeName: k8s-node3 #强制约束将Pod调度到指定的Node节点上
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol
        emptyDir: {} #临时目录
      hostNetwork: true
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: azure-agent
#   name: azure-agent
# spec:
#   ports:
#   - name: tcp-9090-9090
#     nodePort: 0
#     port: 9090
#     protocol: TCP
#     targetPort: 9090
#   selector:
#     app: azure-agent
#   sessionAffinity: None
#   type: ClusterIP