apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: mysql
    qcloud-app: mysql
  name: mysql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: mysql
      qcloud-app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: mysql
        qcloud-app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123456..
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        resources:
          limits:
            cpu: "1"
            memory: 5024Mi
          requests:
            cpu: 10m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vol
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol
        qcloudCbs:
          cbsDiskId: disk-8e6uak12
          fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  clusterIP: 10.3.255.130
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-3306-3306
    nodePort: 30306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    k8s-app: mysql
    qcloud-app: mysql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
