apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: public-nextcloud
    qcloud-app: public-nextcloud
  name: public-nextcloud
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: public-nextcloud
      qcloud-app: public-nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: public-nextcloud
        qcloud-app: public-nextcloud
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: public_nextcloud
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 123456..
        - name: MYSQL_HOST
          value: 10.3.255.130:3306
        - name: NEXTCLOUD_ADMIN_USER
          value: wenqiang.li
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: Lys1314..
        image: nextcloud:17
        imagePullPolicy: IfNotPresent
        name: public-nextcloud
        resources:
          limits:
            cpu: "1"
            memory: 4024Mi
          requests:
            cpu: 10m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/
          name: data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        nfs:
          path: /
          server: 172.16.16.10
---
apiVersion: v1
kind: Service
metadata:
  name: public-nextcloud
  namespace: default
spec:
  clusterIP: 10.3.255.46
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-80-80
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: public-nextcloud
    qcloud-app: public-nextcloud
  sessionAffinity: None
  type: NodePort
