apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tc-agent
  name: tc-agent
spec:
  replicas: 2
  revisionHistoryLimit: 2 #保留的历史记录数，设置为0将清理部署的所有历史记录，无法回滚
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tc-agent
    spec:
      containers:
      - env:
        - name: AGENT_NAME #代理名称
          value: Agent1
        - name: SERVER_URL #服务端访问地址
          value: http://172.16.2.202:30001
        - name: DOCKER_IN_DOCKER
          value: start
        image: jetbrains/teamcity-agent
        imagePullPolicy: IfNotPresent  #拉取策略
        name: tc-agent
        resources: #资源限制
          limits:
            cpu: 4
            memory: 10024Mi
          requests: #代理构建时消耗比较大，尽量分配多点资源
            cpu: 1
            memory: 6096Mi
        securityContext:
          privileged: true #特级权限
        volumeMounts:
        - mountPath: /data/teamcity_agent/conf
          name: vol
        - mountPath: /var/lib/docker
          name: vol
      dnsPolicy: ClusterFirst
      nodeName: k8s-node3 #强制约束将Pod调度到指定的Node节点上
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol
        emptyDir: {} #临时目录
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tc-agent
  name: tc-agent
spec:
  ports:
  - name: tcp-9090-9090
    nodePort: 0
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: tc-agent
  sessionAffinity: None
  type: ClusterIP